### ISSUE TITLE
No 'decorations' folder causes mod load syntax error

### ISSUE THREAD

**Issue by samkatakouzinos** [KuriKai/dhmp#12]
Is there meant to be a 'decorations' folder?  
Without it doomsday engine lists a syntax error.  

![Doomsday_2019-06-18_22-42-05](https://user-images.githubusercontent.com/1305871/59682913-8635f980-921a-11e9-86ef-1de93645390b.png)

**Comment by KuriKai** [comment]
Is this from a build you made yourself?

**Comment by samkatakouzinos** [comment]
This is from a git clone of the repository and a successful run of the bash script. 

The script identifies a folder called decorations in it's arrays yet there is no such folder in the repository. 

I removed the decorations references from the script and gave it another go and successfully loaded in doomsday without error. 

So, is there a decorations folder missing in the repository or is the script identifying a folder that's not needed?

**Comment by KuriKai** [comment]
There is a decorations folder in the zip created on linux. there will be things in it in the future, no models for the decorations have been made yet though.
https://doomwiki.org/wiki/Thing_types#Decorations

Does it look like this in your build?
![Screenshot from 2019-06-19 10-36-17](https://user-images.githubusercontent.com/6791624/59724477-1bb6a500-927e-11e9-90d7-cc417068642c.png)

**Comment by samkatakouzinos** [comment]
It does look like that.
Except that in the decorations.pack folder are the script files from the build folder.

The script doesn't check if the array item exists as a folder first before processing packs within it.
Probably pushd fails and further processing stays at the build folder.

**Comment by KuriKai** [comment]
there were no items in decorations flder, therefore decorations folder did not exist, added dead cacodemon, and now candle, so issue will not occur
