### ISSUE TITLE
mega's "Enter decryption key" error

### ISSUE THREAD

**Issue by BigGammer** [KuriKai/dhmp#2]
Every time I try downloading either the **Medium Resolution textures** or the **Low Resolution textures** from the **High-res Model Project**'s download page, I keep giving me the captioned _"Enter decryption key"_ error dialog box from mega telling me _"The provided key is invalid. Please check that the key is correct or ask the creator of the link again."_, no matter what web browser I'm using. What does this error mean and how can I resolve this issue?

To help make my meaning clear, I took a screenshot of this error and attached it here.

![mega enter decryption key](https://user-images.githubusercontent.com/13742124/29789639-9240c142-8beb-11e7-825b-eb0dddf09e28.jpg)

**Comment by KuriKai** [comment]
What browser are you using?
Does it work on a different browser?

I just attempted to download both packs, and they downloaded sucessfully without having to paste in a decryption key

For the medium, does pasting this in work?
QROyRlMHswWbN86hw1HimFyLc3jCkgHY4to6Lci9aeY

For the high, does pasting this in work?
JNwlOshdOB7c4ua6303clf1GEQ5rbi_IeUePOhC_-ng

**Comment by BigGammer** [comment]
Both of the codes that you sent me as a reply worked once I used the copy-n-paste method on the Decryption key edit line and I've opened both files (both the low and the high-res) in 7-Zip and no errors were found within the downloaded ZIP files. My default internet browser is Firefox (version 5.5.0.3 as of this writing) on Windows 7 Home Premium SP1 64-bit, but I've also tried Internet Explorer version 11.0.45.

**Comment by KuriKai** [comment]
Added the decryption key to the download page in case anyone else encounters the issue

**Comment by chinacity971-source** [comment]
92b1fba1-f594-49cc-ad7d-bb19ee72e949

**Comment by chinacity971-source** [comment]
https://github.com/KuriKai/dhmp/issues/2#issuecomment-3654922674
