### ISSUE TITLE
 Rocket.pack: wrong offset and size

### ISSUE THREAD

**Issue by deus-e-x** [KuriKai/dhmp#3]
Representation of the rocket model in game is messed up. Currently it is drawn up side down, positioned below the floor and oversized. See attached screenshot (DHMP 20181206, Doomsday build 2895).

![doom2-000](https://user-images.githubusercontent.com/45689656/49650359-333de700-fa2c-11e8-91ce-357717b84e97.jpg)

**Comment by KuriKai** [comment]
fixed, will be released in the next pack
