### ISSUE TITLE
Reflections.pack: texture reference issue

### ISSUE THREAD

**Issue by deus-e-x** [KuriKai/dhmp#5]
1. The package info is referencing two textures incorrectly (DHMP 20181206):
e1m1-in.jpg, e1m1-out.jpg

Should be changed to:
e1m1-in.png, e1m1-out.png

2. Probably not an issue: The package does not include a icon.png.

**Comment by KuriKai** [comment]
removed the default reflections as they did not exist
will be fixed in next release
